name: tsunami
author: dvilela
version: 0.1.0
description: A service that tracks events on the Olas ecosystem and autonomously reports
  on it on Twitter and Farcaster.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeibh5bgshii5oqjfuhwmiivfvfqy7fw5pzvarxkpe4qrgivxtc3xym
fingerprint_ignore_patterns: []
agent: dvilela/tsunami:0.1.0:bafybeiev3bno5mpv7jznvkkqava6hg4obzqig4sgq75kmjigyf6x3olbna
number_of_agents: 1
deployment:
  agent:
    ports:
      0:
        8823: 8000
  local:
    volumes:
      0:
        /home/david/Descargas/data: /data
        /home/david/.cache/huggingface: /root/.cache/huggingface
---
public_id: dvilela/tsunami_chained_abci:0.1.0
type: skill
extra:
  params_args:
    args:
      setup: &id001
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0x0000000000000000000000000000000000000000}
        all_participants: ${ALL_PARTICIPANTS:list:[]}
        consensus_threshold: null
      genesis_config: &id002
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
0:
  models:
    benchmark_tool:
      args:
        log_dir: ${LOG_DIR:str:/logs}
    params:
      args:
        setup: *id001
        genesis_config: *id002
        cleanup_history_depth: 1
        cleanup_history_depth_current: null
        drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
        keeper_timeout: 30.0
        max_attempts: 10
        max_healthcheck: 120
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:300}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:30}
        retry_attempts: 400
        retry_timeout: 3
        request_retry_delay: 1.0
        request_timeout: 10.0
        round_timeout_seconds: 30.0
        tweet_evaluation_round_timeout: ${TWEET_EVALUATION_ROUND_TIMEOUT:float:600.0}
        service_id: tsunami
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: 1
        tendermint_check_sleep_delay: 3
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: 5
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:tsunami_tm_0:26656}
        tx_timeout: 10.0
        use_termination: ${USE_TERMINATION:bool:true}
        validate_timeout: 1205
        multisend_batch_size: ${MULTISEND_BATCH_SIZE:int:5}
        ipfs_address: ${IPFS_ADDRESS:str:https://gateway.autonolas.tech/ipfs/}
        default_chain_id: ${DEFAULT_CHAIN_ID:str:ethereum}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:0}
        publish_twitter: ${PUBLISH_TWITTER:bool:false}
        publish_farcaster: ${PUBLISH_FARCASTER:bool:false}
        publish_telegram: ${PUBLISH_TELEGRAM:bool:false}
        service_registry_address_ethereum: ${SERVICE_REGISTRY_ADDRESS_ETHEREUM:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        agent_registry_address_ethereum: ${AGENT_REGISTRY_ADDRESS_ETHEREUM:str:0x2F1f7D38e4772884b88f3eCd8B6b9faCdC319112}
        component_registry_address_ethereum: ${COMPONENT_REGISTRY_ADDRESS_ETHEREUM:str:0x15bd56669F57192a97dF41A2aa8f4403e9491776}
        service_registry_address_gnosis: ${SERVICE_REGISTRY_ADDRESS_GNOSIS:str:0x9338b5153AE39BB89f50468E608eD9d764B755fD}
        initial_block_ethereum: ${INITIAL_BLOCK_ETHEREUM:int:18500000}
        initial_block_gnosis: ${INITIAL_BLOCK_GNOSIS:int:18500000}
        twitter_credentials: ${TWITTER_CREDENTIALS:str:{}}
        event_tracking_enabled: ${EVENT_TRACKING_ENABLED:bool:true}
        repo_tracking_enabled: ${REPO_TRACKING_ENABLED:bool:true}
        omen_tracking_enabled: ${OMEN_TRACKING_ENABLED:bool:true}
        suno_enabled: ${SUNO_ENABLED:bool:true}
        telegram_token: ${TELEGRAM_TOKEN:str:null}
        telegram_chat_id: ${TELEGRAM_CHAT_ID:int:null}
        service_endpoint: ${SERVICE_ENDPOINT:str:https://tsunami.dummy.com/}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${ETHEREUM_LEDGER_RPC:str:http://host.docker.internal:8545}
      chain_id: ${ETHEREUM_LEDGER_CHAIN_ID:int:31337}
      poa_chain: ${ETHEREUM_LEDGER_IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${ETHEREUM_LEDGER_PRICING:str:eip1559}
    gnosis:
      address: ${GNOSIS_LEDGER_RPC:str:http://host.docker.internal:8545}
      chain_id: ${GNOSIS_LEDGER_CHAIN_ID:int:100}
      poa_chain: ${GNOSIS_LEDGER_IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${GNOSIS_LEDGER_PRICING:str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${ACN_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: valory/twitter:0.1.0
type: connection
config:
  access_secret: ${ACCESS_SECRET:str:<access_secret>}
  access_token: ${ACCESS_TOKEN:str:<access_token>}
  auth_token: ${AUTH_TOKEN:str:<auth_token>}
  consumer_key: ${CONSUMER_KEY:str:<consumer_key>}
  consumer_secret: ${CONSUMER_SECRET:str:<consumer_secret>}
  use_staging_api: ${USE_STAGING_API:bool:false}
  staging_api: ${STAGING_API_TWITTER:str:http://host.docker.internal:5000/twitter/create_tweet}
---
public_id: valory/farcaster:0.1.0
type: connection
config:
  farcaster_mnemonic: ${FARCASTER_MNEMONIC:str:<farcaster_mnemonic>}
---
public_id: dvilela/llama:0.1.0
type: connection
config:
  repo_id: ${LLAMA_REPO_ID:str:QuantFactory/Meta-Llama-3-8B-Instruct-GGUF}
  filename: ${LLAMA_FILENAME:str:*Q4_0.gguf}
---
public_id: dvilela/suno:0.1.0
type: connection
config:
  suno_session_id: ${SUNO_SESSION_ID:str:null}
  suno_cookie: ${SUNO_COOKIE:str:null}
---
public_id: dvilela/kv_store:0.1.0
type: connection
config:
  db_path: ${DB_PATH:str:/logs/tsunami.db}
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: ${HTTP_SERVER_HOST:str:0.0.0.0}
  target_skill_id: dvilela/tsunami_chained_abci:0.1.0
