# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv_storage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="kv_storage.proto",
    package="aea.dvilela.kv_storage.v0_1_0",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b"\n\x10kv_storage.proto\x12\x1d\x61\x65\x61.dvilela.kv_storage.v0_1_0\"\x84\x08\n\x10KvStorageMessage\x12y\n\x18\x63reate_or_update_request\x18\x05 \x01(\x0b\x32U.aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_PerformativeH\x00\x12S\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x42.aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Error_PerformativeH\x00\x12\x61\n\x0cread_request\x18\x07 \x01(\x0b\x32I.aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Request_PerformativeH\x00\x12\x63\n\rread_response\x18\x08 \x01(\x0b\x32J.aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_PerformativeH\x00\x12W\n\x07success\x18\t \x01(\x0b\x32\x44.aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Success_PerformativeH\x00\x1a)\n\x19Read_Request_Performative\x12\x0c\n\x04keys\x18\x01 \x03(\t\x1a\xad\x01\n\x1aRead_Response_Performative\x12\x62\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32T.aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_Performative.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\xc3\x01\n%Create_Or_Update_Request_Performative\x12m\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32_.aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_Performative.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a'\n\x14Success_Performative\x12\x0f\n\x07message\x18\x01 \x01(\t\x1a%\n\x12\x45rror_Performative\x12\x0f\n\x07message\x18\x01 \x01(\tB\x0e\n\x0cperformativeb\x06proto3",
)


_KVSTORAGEMESSAGE_READ_REQUEST_PERFORMATIVE = _descriptor.Descriptor(
    name="Read_Request_Performative",
    full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Request_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="keys",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Request_Performative.keys",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=569,
    serialized_end=610,
)

_KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE_DATAENTRY = _descriptor.Descriptor(
    name="DataEntry",
    full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_Performative.DataEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_Performative.DataEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_Performative.DataEntry.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=743,
    serialized_end=786,
)

_KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE = _descriptor.Descriptor(
    name="Read_Response_Performative",
    full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_Performative.data",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE_DATAENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=613,
    serialized_end=786,
)

_KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE_DATAENTRY = _descriptor.Descriptor(
    name="DataEntry",
    full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_Performative.DataEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_Performative.DataEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_Performative.DataEntry.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=743,
    serialized_end=786,
)

_KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE = _descriptor.Descriptor(
    name="Create_Or_Update_Request_Performative",
    full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_Performative.data",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE_DATAENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=789,
    serialized_end=984,
)

_KVSTORAGEMESSAGE_SUCCESS_PERFORMATIVE = _descriptor.Descriptor(
    name="Success_Performative",
    full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Success_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Success_Performative.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=986,
    serialized_end=1025,
)

_KVSTORAGEMESSAGE_ERROR_PERFORMATIVE = _descriptor.Descriptor(
    name="Error_Performative",
    full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Error_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Error_Performative.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=1027,
    serialized_end=1064,
)

_KVSTORAGEMESSAGE = _descriptor.Descriptor(
    name="KvStorageMessage",
    full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="create_or_update_request",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.create_or_update_request",
            index=0,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="error",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.error",
            index=1,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="read_request",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.read_request",
            index=2,
            number=7,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="read_response",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.read_response",
            index=3,
            number=8,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="success",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.success",
            index=4,
            number=9,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _KVSTORAGEMESSAGE_READ_REQUEST_PERFORMATIVE,
        _KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE,
        _KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE,
        _KVSTORAGEMESSAGE_SUCCESS_PERFORMATIVE,
        _KVSTORAGEMESSAGE_ERROR_PERFORMATIVE,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="performative",
            full_name="aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.performative",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=52,
    serialized_end=1080,
)

_KVSTORAGEMESSAGE_READ_REQUEST_PERFORMATIVE.containing_type = _KVSTORAGEMESSAGE
_KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE_DATAENTRY.containing_type = (
    _KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE
)
_KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE.fields_by_name[
    "data"
].message_type = _KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE_DATAENTRY
_KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE.containing_type = _KVSTORAGEMESSAGE
_KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE_DATAENTRY.containing_type = (
    _KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE
)
_KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE.fields_by_name[
    "data"
].message_type = _KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE_DATAENTRY
_KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE.containing_type = (
    _KVSTORAGEMESSAGE
)
_KVSTORAGEMESSAGE_SUCCESS_PERFORMATIVE.containing_type = _KVSTORAGEMESSAGE
_KVSTORAGEMESSAGE_ERROR_PERFORMATIVE.containing_type = _KVSTORAGEMESSAGE
_KVSTORAGEMESSAGE.fields_by_name[
    "create_or_update_request"
].message_type = _KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE
_KVSTORAGEMESSAGE.fields_by_name[
    "error"
].message_type = _KVSTORAGEMESSAGE_ERROR_PERFORMATIVE
_KVSTORAGEMESSAGE.fields_by_name[
    "read_request"
].message_type = _KVSTORAGEMESSAGE_READ_REQUEST_PERFORMATIVE
_KVSTORAGEMESSAGE.fields_by_name[
    "read_response"
].message_type = _KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE
_KVSTORAGEMESSAGE.fields_by_name[
    "success"
].message_type = _KVSTORAGEMESSAGE_SUCCESS_PERFORMATIVE
_KVSTORAGEMESSAGE.oneofs_by_name["performative"].fields.append(
    _KVSTORAGEMESSAGE.fields_by_name["create_or_update_request"]
)
_KVSTORAGEMESSAGE.fields_by_name[
    "create_or_update_request"
].containing_oneof = _KVSTORAGEMESSAGE.oneofs_by_name["performative"]
_KVSTORAGEMESSAGE.oneofs_by_name["performative"].fields.append(
    _KVSTORAGEMESSAGE.fields_by_name["error"]
)
_KVSTORAGEMESSAGE.fields_by_name[
    "error"
].containing_oneof = _KVSTORAGEMESSAGE.oneofs_by_name["performative"]
_KVSTORAGEMESSAGE.oneofs_by_name["performative"].fields.append(
    _KVSTORAGEMESSAGE.fields_by_name["read_request"]
)
_KVSTORAGEMESSAGE.fields_by_name[
    "read_request"
].containing_oneof = _KVSTORAGEMESSAGE.oneofs_by_name["performative"]
_KVSTORAGEMESSAGE.oneofs_by_name["performative"].fields.append(
    _KVSTORAGEMESSAGE.fields_by_name["read_response"]
)
_KVSTORAGEMESSAGE.fields_by_name[
    "read_response"
].containing_oneof = _KVSTORAGEMESSAGE.oneofs_by_name["performative"]
_KVSTORAGEMESSAGE.oneofs_by_name["performative"].fields.append(
    _KVSTORAGEMESSAGE.fields_by_name["success"]
)
_KVSTORAGEMESSAGE.fields_by_name[
    "success"
].containing_oneof = _KVSTORAGEMESSAGE.oneofs_by_name["performative"]
DESCRIPTOR.message_types_by_name["KvStorageMessage"] = _KVSTORAGEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KvStorageMessage = _reflection.GeneratedProtocolMessageType(
    "KvStorageMessage",
    (_message.Message,),
    {
        "Read_Request_Performative": _reflection.GeneratedProtocolMessageType(
            "Read_Request_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _KVSTORAGEMESSAGE_READ_REQUEST_PERFORMATIVE,
                "__module__": "kv_storage_pb2",
                # @@protoc_insertion_point(class_scope:aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Request_Performative)
            },
        ),
        "Read_Response_Performative": _reflection.GeneratedProtocolMessageType(
            "Read_Response_Performative",
            (_message.Message,),
            {
                "DataEntry": _reflection.GeneratedProtocolMessageType(
                    "DataEntry",
                    (_message.Message,),
                    {
                        "DESCRIPTOR": _KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE_DATAENTRY,
                        "__module__": "kv_storage_pb2",
                        # @@protoc_insertion_point(class_scope:aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_Performative.DataEntry)
                    },
                ),
                "DESCRIPTOR": _KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE,
                "__module__": "kv_storage_pb2",
                # @@protoc_insertion_point(class_scope:aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Read_Response_Performative)
            },
        ),
        "Create_Or_Update_Request_Performative": _reflection.GeneratedProtocolMessageType(
            "Create_Or_Update_Request_Performative",
            (_message.Message,),
            {
                "DataEntry": _reflection.GeneratedProtocolMessageType(
                    "DataEntry",
                    (_message.Message,),
                    {
                        "DESCRIPTOR": _KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE_DATAENTRY,
                        "__module__": "kv_storage_pb2",
                        # @@protoc_insertion_point(class_scope:aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_Performative.DataEntry)
                    },
                ),
                "DESCRIPTOR": _KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE,
                "__module__": "kv_storage_pb2",
                # @@protoc_insertion_point(class_scope:aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Create_Or_Update_Request_Performative)
            },
        ),
        "Success_Performative": _reflection.GeneratedProtocolMessageType(
            "Success_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _KVSTORAGEMESSAGE_SUCCESS_PERFORMATIVE,
                "__module__": "kv_storage_pb2",
                # @@protoc_insertion_point(class_scope:aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Success_Performative)
            },
        ),
        "Error_Performative": _reflection.GeneratedProtocolMessageType(
            "Error_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _KVSTORAGEMESSAGE_ERROR_PERFORMATIVE,
                "__module__": "kv_storage_pb2",
                # @@protoc_insertion_point(class_scope:aea.dvilela.kv_storage.v0_1_0.KvStorageMessage.Error_Performative)
            },
        ),
        "DESCRIPTOR": _KVSTORAGEMESSAGE,
        "__module__": "kv_storage_pb2",
        # @@protoc_insertion_point(class_scope:aea.dvilela.kv_storage.v0_1_0.KvStorageMessage)
    },
)
_sym_db.RegisterMessage(KvStorageMessage)
_sym_db.RegisterMessage(KvStorageMessage.Read_Request_Performative)
_sym_db.RegisterMessage(KvStorageMessage.Read_Response_Performative)
_sym_db.RegisterMessage(KvStorageMessage.Read_Response_Performative.DataEntry)
_sym_db.RegisterMessage(KvStorageMessage.Create_Or_Update_Request_Performative)
_sym_db.RegisterMessage(
    KvStorageMessage.Create_Or_Update_Request_Performative.DataEntry
)
_sym_db.RegisterMessage(KvStorageMessage.Success_Performative)
_sym_db.RegisterMessage(KvStorageMessage.Error_Performative)


_KVSTORAGEMESSAGE_READ_RESPONSE_PERFORMATIVE_DATAENTRY._options = None
_KVSTORAGEMESSAGE_CREATE_OR_UPDATE_REQUEST_PERFORMATIVE_DATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
